{
  imports = [
    ./arr
    ./blocky.nix
    ./dashboard.nix
    ./firefox-syncserver.nix
    ./forgejo.nix
    ./grafana.nix
    ./headplane.nix
    ./headscale.nix
    ./immich.nix
    ./jellyfin
    ./jellyseerr
    ./journald-loki.nix
    ./llama-cpp.nix
    ./nixos-info-collector.nix
    ./pipewire
    ./qbittorrent.nix
    ./rapl-collector.nix
    ./tailscale-funnel.nix
    ./tailscale-tls.nix
    ./vaultwarden.nix
    ./zitadel.nix
  ];
}
