name: nix

on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "flake.lock"
      - "flake.nix"
  pull_request:
    paths:
      - "**.nix"
      - "flake.lock"
      - "flake.nix"
  workflow_dispatch:

jobs:
  nix:
    name: checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Restore Nix store cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: nix-${{ hashFiles('flake.lock') }}
          restore-keys: nix-

      - name: Read Nix cache config
        id: caches
        run: |
          echo "substituters=$(jq -r '.substituters | join(" ")' system/nix/cache.json)" >> "$GITHUB_OUTPUT"
          echo "trusted-public-keys=$(jq -r '."trusted-public-keys" | join(" ")' system/nix/cache.json)" >> "$GITHUB_OUTPUT"

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            substituters = ${{ steps.caches.outputs.substituters }}
            trusted-public-keys = ${{ steps.caches.outputs.trusted-public-keys }}

      - name: Nix flake check
        run: |
          nix flake check
