name: Update Nix Flake
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes

      - name: Update flake.lock
        run: |
          nix flake update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "flake.lock: update"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-flake
          delete-branch: true
          title: "flake.lock: update"
          body: |
            This PR was automatically generated by the GitHub Actions workflow `Update Nix Flake'.
            It updates the `flake.lock` file to the latest version.

            Checks:
            - [ ] CI
            - [ ] Checkout and upgrade locally
          labels: |
            flake
            update
            automated
          assignees: amadejkastelic
          reviewers: amadejkastelic
          draft: false
